
server:
  port: 8001

mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis所在路径
  type-aliases-package: com.wn.springcloud_api.entity #entity别名类
#  mapper-locations:
#    - classpath:mybatis/mapper/**/*.xml #mapper映射文件

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
  application:
    name: microservicecloud-dept

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix
    prefer-ip-address: true

info:
  app:
    name: microservicecloud
  company:
    name: www.baidu.com





